version: '3.8'

services:

  mysql:
    image: mysql:8
    container_name: cowpro-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: cowpro
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./sharechannel_backend
    container_name: cowpro-backend
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cowpro
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234

  fastapi:
    build:
      context: ./tuya-lock-api
    container_name: cowpro-fastapi
    ports:
      - "8000:8000"

volumes:
  mysql_data:

